<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>dkFramework</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<?php
	echo $include_script;
	?>
    </head>

    <body>

        <header>
            <table border=1 cellpadding=0 cellspacing=0>
            <tbody>
            <tr>
                <td>메뉴1</td>
                <td>메뉴2</td>
                <td>메뉴3</td>
            </tr>
            <tbody>
            </table>
        </header>

        <content>
            <?php
                echo $contents;
            ?>
        </content>

        <footer>
            <table border=1 cellpadding=0 cellspacing=0 width=100%>
            <tbody>
            <tr>
                <td align=center>bottom</td>
            </tr>
            <tbody>
            </table>
        </footer>

    </body>
</html>
